name: every 5 minutes

on:
  schedule:
    - cron: "45 4 * * *"   # 매일 13:45 (KST)
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call ASP endpoint (no token)
        run: |
          curl -X POST https://hohoschool.com/hohoeduapi/user_login_202508.html \
            -H "Content-Type: application/json" \
            -d '{"job":"every-5m"}'
